name: Build & test
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Setup database
      run: "docker run --platform linux/amd64 --name wandermate-db -p 5431:5432 -e POSTGRES_DB=wandermate -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=postgres -d postgres:15.1"
    - name: Build & Test with Maven
      run: "mvn clean verify"
