name: Build & test
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Setup database
      uses: docker://postgres:13.3
      with:
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: wandermate
        ports:
          5431:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    - name: Build & Test with Maven
      run: mvn clean verify
